call activate batchenv
python.exe "initiate_batch.py" "backfill" "M"

python.exe "make_0a_ibes_roe.py" "backfill" "M"
python.exe "make_1a_ibes_edp.py" "backfill" "M"
python.exe "make_2b_SustG.py" "backfill" "M"
python.exe "make_3b_GARP.py" "backfill" "M"
python.exe "make_5yrRel_CFO2EV.py" "backfill" "M"
python.exe "make_5yrRel_CFO2px.py" "backfill" "M"
python.exe "make_5yrRel_EBITDA2px.py" "backfill" "M"
python.exe "make_Accruals.py" "backfill" "M"
python.exe "make_ARDays.py" "backfill" "M"
python.exe "make_AxiomaMomentum.py" "backfill" "M"
python.exe "make_CAcqR.py" "backfill" "M"
python.exe "make_EarnRev.py" "backfill" "M"
python.exe "make_EVEbitda.py" "backfill" "M"
python.exe "make_FCFROIC.py" "backfill" "M"
python.exe "make_GPOA.py" "backfill" "M"
python.exe "make_IntC.py" "backfill" "M"
python.exe "make_LTDebt.py" "backfill" "M"
python.exe "make_margin.py" "backfill" "M"
python.exe "make_OpLev.py" "backfill" "M"
python.exe "make_Ratios.py" "backfill" "M"
python.exe "make_ROIC.py" "backfill" "M"
python.exe "make_Starmine.py" "backfill" "M"
python.exe "make_Value.py" "backfill" "M"
call deactivate
